name: build-python-wheels

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.10']
        target: [x86_64, aarch64, universal2-apple-darwin]

    steps:
      - name: Check out the main repository
        uses: actions/checkout@v4

      - name: Check out regorus code
        uses: actions/checkout@v4
        with:
          repository: GCH-SC/regorus
          path: .
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build Python extension
        run: |
          cargo fetch
          cargo clippy --all-targets --no-deps -- -Dwarnings
          cargo build --release --target ${{ matrix.host.target }} --frozen
        working-directory: bindings/python

      - name: Build wheels
        uses: PyO3/maturin-action@63b75c597b83e247fbf4fb7719801cc4220ae9f3 # v1.43.0
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --manifest-path bindings/python/Cargo.toml --offline --strip
          sccache: 'true'
      
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist

  
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        target: [x86_64, aarch64, armv7]

    steps:
      - name: Check out the main repository
        uses: actions/checkout@v4
      
      - name: Check out regorus code
        uses: actions/checkout@v4
        with:
          repository: GCH-SC/regorus
          path: .
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
        
      - name: Build Python extension
        run: |
          cargo fetch
          cargo clippy --all-targets --no-deps -- -Dwarnings
          cargo build --release --target ${{ matrix.target }} --frozen
        working-directory: bindings/python

      - name: Build wheels
        uses: PyO3/maturin-action@63b75c597b83e247fbf4fb7719801cc4220ae9f3 # v1.43.0
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --manifest-path bindings/python/Cargo.toml --offline --strip
          sccache: 'true'
          manylinux: auto
      
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
    
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.10']
        target: [x64, x86]

    steps:
      - name: Check out the main repository
        uses: actions/checkout@v4

      - name: Check out regorus code
        uses: actions/checkout@v4
        with:
          repository: GCH-SC/regorus
          path: .
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: ${{ matrix.target }}

      - name: Build Python extension
        run: |
          cargo fetch
          cargo clippy --all-targets --no-deps -- -Dwarnings
          cargo build --release --target ${{ matrix.host.target }} --frozen
        working-directory: bindings/python

      - name: Build wheels
        uses: PyO3/maturin-action@63b75c597b83e247fbf4fb7719801cc4220ae9f3 # v1.43.0
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --manifest-path bindings/python/Cargo.toml --frozen --strip
          sccache: 'true'
      
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: dist
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [linux, macos, windows]
    steps:
      - name: Check out the main repository
        uses: actions/checkout@v4
    
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: wheels
      
      - name: Publish to PyPI
        uses: PyO3/maturin-action@63b75c597b83e247fbf4fb7719801cc4220ae9f3 # v1.43.0
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        with:
          command: upload
          args: --non-interactive --skip-existing *